config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    get :favorites, on: :collection
  end
  resources :favorites, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture

  validates_uniqueness_of :picture_id, scope: :user_id
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image,  presence: true
  validates :content, presence: true, length: { maximum: 255 }
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  # before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  before_action :forbid_login_user
  private
  def login_required
    redirect_to new_session_path unless current_user
    end
    def forbid_login_user
      if @current_user
      flash[:notice] = "ログインしています"
      else
      flash[:notice] = "ログインしていません"
      end
    end
  end
  def authenticate_user
    if logged_in?
      unless current_user.id == @picture.user_id
        flash[:notice] = "権限がありません。"
        redirect_to pictures_path
      end
    else
      redirect_to new_user_path, notice:"ログインが必要です"
    end
  end
  def ensure_current_user
    if logged_in?
      unless current_user.id == params[:id].to_i
        flash[:notice] = "権限がありません。"
        redirect_to pictures_path
      end
    else
      redirect_to new_user_path, notice:"ログインが必要です"
    end
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end

  private
  def set_picture
    @picture = Picture.find(params[:picture_id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]
  before_action :authenticate_user, only:[:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def show
    if logged_in?
      @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    else
      redirect_to new_user_path, notice:"ログインが必要です"
    end
  end

  def new
    @picture = Picture.new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def create
    @picture = Picture.new(picture_params)
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver
        redirect_to pictures_path, notice: "投稿しました！"
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @picture.update(pictures_params)
      redirect_to new_picture_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to  new_picture_path
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content, :user)
  end
  def ensure_user
    @pictures = current_user.pictures
    @picture = @pictures.find_by(id: params[:id])
    redirect_to new_picture_path unless @picture
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_current_user,only:[:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "登録が完了しました！"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @pictures = @user.pictures

    favorites = Favorite.where(user_id: current_user.id).pluck(:picture_id)
    @favorite_list = Picture.find(favorites)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # @user.name = params[:name]
    # @user.email = params[:email]
    # @user.image = "#{@user.id}.jpg"
    # if params[:image]
    #   image = param[:image]
    #   File.binwrite("public/uploads/user/image/#{@user.image}",image.read)
    # end
    if @user.update(user_params)
      flash[:notice] = "情報を編集しました！"
      redirect_to user_path
    else
      render :edit
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to new_user_path, notice:"ユーザー情報を削除しました！"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    <%= link_to "プロフィール", user_path(current_user.id) %>
    <%= link_to "投稿一覧", pictures_path %>
    <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
    <%= link_to "ユーザー登録", new_user_path %>
    <%= link_to "ログイン", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="field">
        <%= form.label :image %>
        <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
        <%= form.file_field :image, class: 'form-control' %>
        <%= form.hidden_field :image_cache %>
      </div>

      <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit class: "btn btn-primary"%>
      </div>
    </div>
  </div>
<% end %>

app/views/pictures/comfirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <p>内容:<%= @picture.content %></p>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <p>内容:<%= @picture.content %></p>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>みんなの投稿</h1>
<%= link_to '新規投稿', new_picture_path, class: 'btn btn-primary' %>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>みんなの写真</th>
      <th>内容</th>
      <th>投稿者</th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= image_tag picture.image.url %></td>
        <td><%= picture.content %></td>
        <td><%= picture.user.name %></td>
        <td><%= link_to 'Show', picture %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', picture: @picture %>

<%= link_to '戻る', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>
<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<% if @picture.user == current_user %>
  <%= link_to '編集', edit_picture_path(@picture.id) %>
  <%= link_to "削除", picture_path(@picture.id), method: :delete, data: { confirm: '本当に削除しますか?' } %>
<% end %>
<div class="show_back">
  <%= link_to 'Back', pictures_path %>
</div>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <div class="submit_record">
    <p><%= f.submit "内容変更" %></p>
  </div>
<% end %>

<%= link_to 'Back', @user %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <div class="submit_record">
    <p><%= f.submit "登録" %></p>
  </div>
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h1><%= @user.name %>のページ</h1>
      <p>メールアドレス: <%= @user.email %></p>
      <% if @user.image? %>
        <%= image_tag @user.image.url if @user.image? %>
      <% end %>
    </div>
    <div class="choice">
      <% if @user.id==@current_user.id %>
        <%= link_to "編集", edit_user_path(@user), class: 'btn btn-primary' %>
        <%= link_to '削除', user_path(@user), method: :delete, class: 'btn btn-danger', data: { confirm: '本当に削除しますか?' } %>
    </div>
    <div class="favarite_list">
      <h4>お気に入りした写真たち</h4>
      <table>
        <tr>
        <% if @favorite_list.present? %>
          <% @favorite_list.each do |picture| %>
              <td><%= image_tag picture.image.url %></td>
              <td><%= picture.content %></td>
          <% end %>
        <% end %>
        </tr>
      </table>
    <div class="new_post">
      <%= link_to "新しく写真を投稿する", new_picture_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
    </div>
  </div>
</div>